# Generated by Django 3.0.6 on 2020-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('ideal_value', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
