# Generated by Django 3.0.6 on 2020-11-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201017_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_type', models.IntegerField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Parameter')),
            ],
        ),
    ]
