# Generated by Django 3.0.6 on 2020-11-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201106_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='plantation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Plantation'),
            preserve_default=False,
        ),
    ]
