# Generated by Django 3.0.6 on 2020-11-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201111_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_responsible',
        ),
    ]
